# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2eb335467b03e865518d14e791b7b76a1a972275fb0b0f6fe8051c830dc100f86730d87ad953f4d223d8ad8ed47b66d48ba1eae139a4fbe97e323fd3f6120d1

test:
  secret_key_base: 142c1c4bbd5c1ab65275dd6cc6b1a8c48ca14dcd3cee471c7c50f95a0c8f3488fd0c81648097e198bff75dc70e309a251422af2446f2e5a303ab8034286074a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
